aws:
  region: us-west-2
  s3BucketName: mastodon-dns-verfication_service
  verificationFileName: verfication_service.json
app:
  verificationTxtRecordName: "mastodon_ownership_key"
  alwaysRecreate: true

