aws:
  region: us-west-2
  s3BucketName: mastodon-dns-verification
  verificationFileName: domain_information_test.json
app:
  verificationTxtRecordName: "mastodon_ownership_key_test"
  alwaysRecreate: false
network:
  owned_hosts:
    - 34.217.225.51
  owned_cnames:
    - spons.us.
