aws:
  region: us-west-2
  s3BucketName: mastodon-dns-verification
  verificationFileName: domain_information.json
app:
  verificationTxtRecordName: "mastodon_ownership_key"
  alwaysRecreate: false
network:
  owned_hosts:
    - 34.217.225.51
  owned_cnames:
    - spons.us.

le_settings:
  admin_email: "admin@amoslabs.cloud"
  private_key_location: "C:\\mastodon\\private-key.pem"
  key_auth: asufficientlylongenoughstringwithenoughentropy

